export const DUMMY_DATA = [
	'How to bake a cake',
	'How to train a dog',
	'How to learn programming',
	'How to lose weight',
	'How to make coffee',
	'How to plant a tree',
	'How to write a resume',
	'How to start a business',
	'How to cook pasta',
	'How to meditate',
	'How to change a tire',
	'How to tie a tie',
	'How to make sushi',
	'How to paint a room',
	'How to build a website',
	'How to sew a dress',
	'How to play guitar',
	'How to do yoga',
	'How to invest in stocks',
	'How to grow tomatoes',
	'When to plant flowers',
	'When to harvest apples',
	'When to water plants',
	'When to visit Japan',
	'When to see a doctor',
	'When to start exercising',
	'When to prune roses',
	'When to change oil',
	'When to apply sunscreen',
	'When to get married',
	'When to retire',
	'When to start a family',
	'When to buy a house',
	'When to take vitamins',
	'When to renew passport',
	'When to travel to Europe',
	'Why should you exercise',
	'Why should you vote',
	'Why should you read books',
	'Why should you meditate',
	'Why should you eat healthy',
	'Why should you save money',
	'Why should you recycle',
	'Why should you learn a language',
	'Why should you volunteer',
	'Why should you drink water',
	'Why should you get vaccinated',
	'Why should you sleep well',
	'Why should you study history',
	'Why should you wear sunscreen',
];
